export type HeroRole = "Assassin" | "Fighter" | "Mage" | "Marksman" | "Support" | "Tank";
export type HeroLane = "EXP Lane" | "Gold Lane" | "Mid Lane" | "Jungler" | "Roamer";

export interface Hero {
  id: string;
  name: string;
  role: HeroRole[];
  lane: HeroLane[];
  image: string;
  winrate?: number;
}

export const MLBB_HEROES: Hero[] = [
  // --- TANK ---
  { id: "akai", name: "Akai", role: ["Tank"], lane: ["Roamer", "Jungler"], image: "/heroes/akai.png", winrate: 0 },
  { id: "alice", name: "Alice", role: ["Tank", "Mage"], lane: ["EXP Lane", "Mid Lane"], image: "/heroes/alice.png", winrate: 45 },
  { id: "atlas", name: "Atlas", role: ["Tank", "Support"], lane: ["Roamer"], image: "/heroes/atlas.png", winrate: 0 },
  { id: "barats", name: "Barats", role: ["Tank", "Fighter"], lane: ["Jungler"], image: "/heroes/barats.png", winrate: 0 },
  { id: "baxia", name: "Baxia", role: ["Tank"], lane: ["Jungler"], image: "/heroes/baxia.png", winrate: 38 },
  { id: "belerick", name: "Belerick", role: ["Tank"], lane: ["Roamer", "EXP Lane"], image: "/heroes/belerick.png", winrate: 100 },
  { id: "edith", name: "Edith", role: ["Tank", "Marksman"], lane: ["EXP Lane", "Roamer"], image: "/heroes/edith.png", winrate: 0 },
  { id: "esmeralda", name: "Esmeralda", role: ["Tank", "Mage"], lane: ["EXP Lane"], image: "/heroes/esmeralda.png", winrate: 0 },
  { id: "franco", name: "Franco", role: ["Tank", "Support"], lane: ["Roamer"], image: "/heroes/franco.png", winrate: 0 },
  { id: "fredrinn", name: "Fredrinn", role: ["Tank", "Fighter"], lane: ["Jungler", "EXP Lane"], image: "/heroes/fredrinn.png", winrate: 52 },
  { id: "gatotkaca", name: "Gatotkaca", role: ["Tank", "Fighter"], lane: ["EXP Lane", "Roamer"], image: "/heroes/gatotkaca.png", winrate: 40 },
  { id: "gloo", name: "Gloo", role: ["Tank"], lane: ["Roamer"], image: "/heroes/gloo.png", winrate: 65 },
  { id: "grock", name: "Grock", role: ["Tank", "Fighter"], lane: ["Roamer", "EXP Lane"], image: "/heroes/grock.png", winrate: 20 },
  { id: "hilda", name: "Hilda", role: ["Tank", "Fighter"], lane: ["Roamer", "EXP Lane"], image: "/heroes/hilda.png", winrate: 33 },
  { id: "hylos", name: "Hylos", role: ["Tank", "Support"], lane: ["Roamer", "Jungler"], image: "/heroes/hylos.png", winrate: 44 },
  { id: "johnson", name: "Johnson", role: ["Tank", "Support"], lane: ["Roamer"], image: "/heroes/johnson.png", winrate: 0 },
  { id: "khufra", name: "Khufra", role: ["Tank", "Support"], lane: ["Roamer"], image: "/heroes/khufra.png", winrate: 100 },
  { id: "kalea", name: "Kalea", role: ["Tank"], lane: ["Roamer"], image: "/heroes/kalea.png", winrate: 58 },
  { id: "lolita", name: "Lolita", role: ["Tank", "Support"], lane: ["Roamer"], image: "/heroes/lolita.png", winrate: 0 },
  { id: "minotaur", name: "Minotaur", role: ["Tank", "Support"], lane: ["Roamer"], image: "/heroes/minotaur.png", winrate: 0 },
  { id: "terizla", name: "Terizla", role: ["Fighter", "Tank"], lane: ["EXP Lane"], image: "/heroes/terizla.png", winrate: 33 },
  { id: "tigreal", name: "Tigreal", role: ["Tank", "Support"], lane: ["Roamer"], image: "/heroes/tigreal.png", winrate: 0 },
  { id: "uranus", name: "Uranus", role: ["Tank"], lane: ["EXP Lane"], image: "/heroes/uranus.png", winrate: 23 },

  // --- FIGHTER ---
  { id: "aldous", name: "Aldous", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/aldous.png", winrate: 0 },
  { id: "alpha", name: "Alpha", role: ["Fighter"], lane: ["Jungler", "EXP Lane"], image: "/heroes/alpha.png", winrate: 0 },
  { id: "alucard", name: "Alucard", role: ["Fighter", "Assassin"], lane: ["Jungler"], image: "/heroes/alucard.png", winrate: 0 },
  { id: "argus", name: "Argus", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/argus.png", winrate: 0 },
  { id: "arlott", name: "Arlott", role: ["Fighter", "Assassin"], lane: ["EXP Lane", "Roamer"], image: "/heroes/arlott.png", winrate: 91 },
  { id: "aulus", name: "Aulus", role: ["Fighter"], lane: ["Jungler"], image: "/heroes/aulus.png", winrate: 0 },
  { id: "badang", name: "Badang", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/badang.png", winrate: 33 },
  { id: "balmond", name: "Balmond", role: ["Fighter"], lane: ["Jungler", "EXP Lane"], image: "/heroes/balmond.png", winrate: 0 },
  { id: "bane", name: "Bane", role: ["Fighter", "Mage"], lane: ["EXP Lane", "Mid Lane"], image: "/heroes/bane.png", winrate: 0 },
  { id: "benedetta", name: "Benedetta", role: ["Assassin", "Fighter"], lane: ["EXP Lane", "Jungler"], image: "/heroes/benedetta.png", winrate: 0 },
  { id: "chou", name: "Chou", role: ["Fighter"], lane: ["EXP Lane", "Roamer"], image: "/heroes/chou.png", winrate: 27 },
  { id: "cici", name: "Cici", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/cici.png", winrate: 33 },
  { id: "dyrroth", name: "Dyrroth", role: ["Fighter"], lane: ["EXP Lane", "Jungler"], image: "/heroes/dyrroth.png", winrate: 0 },
  { id: "freya", name: "Freya", role: ["Fighter"], lane: ["Gold Lane", "EXP Lane"], image: "/heroes/freya.png", winrate: 60 },
  { id: "guinevere", name: "Guinevere", role: ["Fighter"], lane: ["EXP Lane", "Jungler"], image: "/heroes/guinevere.png", winrate: 69 },
  { id: "jawhead", name: "Jawhead", role: ["Fighter"], lane: ["EXP Lane", "Roamer", "Jungler"], image: "/heroes/jawhead.png", winrate: 0 },
  { id: "julian", name: "Julian", role: ["Fighter", "Mage"], lane: ["Jungler", "EXP Lane", "Mid Lane"], image: "/heroes/julian.png", winrate: 0 },
  { id: "khaleed", name: "Khaleed", role: ["Fighter"], lane: ["Roamer", "EXP Lane"], image: "/heroes/khaleed.png", winrate: 22 },
  { id: "lapu-lapu", name: "Lapu-Lapu", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/lapu_lapu.png", winrate: 50 },
  { id: "leomord", name: "Leomord", role: ["Fighter"], lane: ["Jungler"], image: "/heroes/leomord.png", winrate: 61 },
  { id: "lukas", name: "Lukas", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/lukas.png", winrate: 33 },
  { id: "martis", name: "Martis", role: ["Fighter"], lane: ["Jungler", "EXP Lane"], image: "/heroes/martis.png", winrate: 0 },
  { id: "masha", name: "Masha", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/masha.png", winrate: 60 },
  { id: "minsitthar", name: "Minsitthar", role: ["Fighter", "Support"], lane: ["EXP Lane", "Roamer"], image: "/heroes/minsitthar.png", winrate: 0 },
  { id: "paquito", name: "Paquito", role: ["Fighter", "Assassin"], lane: ["EXP Lane", "Jungler"], image: "/heroes/paquito.png", winrate: 0 },
  { id: "phoveus", name: "Phoveus", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/phoveus.png", winrate: 73 },
  { id: "roger", name: "Roger", role: ["Fighter", "Marksman"], lane: ["Jungler", "Gold Lane"], image: "/heroes/roger.png", winrate: 0 },
  { id: "ruby", name: "Ruby", role: ["Fighter", "Tank"], lane: ["EXP Lane", "Roamer"], image: "/heroes/ruby.png", winrate: 0 },
  { id: "silvanna", name: "Silvanna", role: ["Fighter", "Mage"], lane: ["EXP Lane"], image: "/heroes/silvanna.png", winrate: 0 },
  { id: "sun", name: "Sun", role: ["Fighter"], lane: ["EXP Lane", "Jungler"], image: "/heroes/sun.png", winrate: 0 },
  { id: "sora", name: "Sora", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/sora.png", winrate: 46 },
  { id: "thamuz", name: "Thamuz", role: ["Fighter"], lane: ["EXP Lane", "Jungler"], image: "/heroes/thamuz.png", winrate: 0 },
  { id: "x-borg", name: "X.Borg", role: ["Fighter"], lane: ["EXP Lane", "Jungler"], image: "/heroes/x_borg.png", winrate: 0 },
  { id: "yin", name: "Yin", role: ["Fighter", "Assassin"], lane: ["Jungler", "EXP Lane"], image: "/heroes/yin.png", winrate: 0 },
  { id: "yu-zhong", name: "Yu Zhong", role: ["Fighter"], lane: ["EXP Lane"], image: "/heroes/yu-zhong.png", winrate: 50 },
  { id: "zilong", name: "Zilong", role: ["Fighter", "Assassin"], lane: ["EXP Lane"], image: "/heroes/zilong.png", winrate: 0 },

  // --- ASSASSIN ---
  { id: "aamon", name: "Aamon", role: ["Assassin"], lane: ["Jungler"], image: "/heroes/aamon.png", winrate: 0 },
  { id: "fanny", name: "Fanny", role: ["Assassin"], lane: ["Jungler"], image: "/heroes/fanny.png", winrate: 66 },
  { id: "gusion", name: "Gusion", role: ["Assassin", "Mage"], lane: ["Jungler", "Mid Lane"], image: "/heroes/gusion.png", winrate: 0 },
  { id: "hanzo", name: "Hanzo", role: ["Assassin"], lane: ["Jungler"], image: "/heroes/hanzo.png", winrate: 0 },
  { id: "harley", name: "Harley", role: ["Assassin", "Mage"], lane: ["Jungler"], image: "/heroes/harley.png", winrate: 50 },
  { id: "hayabusa", name: "Hayabusa", role: ["Assassin"], lane: ["Jungler"], image: "/heroes/hayabusa.png", winrate: 0 },
  { id: "helcurt", name: "Helcurt", role: ["Assassin"], lane: ["Jungler", "Roamer"], image: "/heroes/helcurt.png", winrate: 50 },
  { id: "joy", name: "Joy", role: ["Assassin"], lane: ["Jungler", "EXP Lane"], image: "/heroes/joy.png", winrate: 0 },
  { id: "karina", name: "Karina", role: ["Assassin", "Mage"], lane: ["Jungler"], image: "/heroes/karina.png", winrate: 0 },
  { id: "lancelot", name: "Lancelot", role: ["Assassin"], lane: ["Jungler"], image: "/heroes/lancelot.png", winrate: 66 },
  { id: "lesley", name: "Lesley", role: ["Marksman", "Assassin"], lane: ["Gold Lane"], image: "/heroes/lesley.png", winrate: 0 },
  { id: "ling", name: "Ling", role: ["Assassin"], lane: ["Jungler"], image: "/heroes/ling.png", winrate: 0 },
  { id: "natalia", name: "Natalia", role: ["Assassin"], lane: ["Roamer", "Jungler"], image: "/heroes/natalia.png", winrate: 0 },
  { id: "nolan", name: "Nolan", role: ["Assassin"], lane: ["Jungler"], image: "/heroes/nolan.png", winrate: 0 },
  { id: "saber", name: "Saber", role: ["Assassin"], lane: ["Jungler", "Roamer"], image: "/heroes/saber.png", winrate: 0 },
  { id: "selena", name: "Selena", role: ["Assassin", "Mage"], lane: ["Roamer", "Mid Lane"], image: "/heroes/selena.png", winrate: 33 },
  { id: "suyou", name: "Suyou", role: ["Assassin", "Fighter"], lane: ["Jungler", "EXP Lane"], image: "/heroes/suyou.png", winrate: 34 },
  { id: "yi-sun-shin", name: "Yi Sun-shin", role: ["Assassin", "Marksman"], lane: ["Gold Lane", "Jungler"], image: "/heroes/yi_sun_shin.png", winrate: 35 },

  // --- MAGE ---
  { id: "aurora", name: "Aurora", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/aurora.png", winrate: 0 },
  { id: "cecilion", name: "Cecilion", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/cecilion.png", winrate: 0 },
  { id: "chang-e", name: "Chang'e", role: ["Mage"], lane: ["Mid Lane", "Gold Lane"], image: "/heroes/chang_e.png", winrate: 0 },
  { id: "cyclops", name: "Cyclops", role: ["Mage"], lane: ["Mid Lane", "Jungler"], image: "/heroes/cyclops.png", winrate: 0 },
  { id: "eudora", name: "Eudora", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/eudora.png", winrate: 0 },
  { id: "gord", name: "Gord", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/gord.png", winrate: 100 },
  { id: "harith", name: "Harith", role: ["Mage"], lane: ["Gold Lane", "Mid Lane", "Jungler"], image: "/heroes/harith.png", winrate: 50 },
  { id: "kagura", name: "Kagura", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/kagura.png", winrate: 0 },
  { id: "kimmy", name: "Kimmy", role: ["Marksman", "Mage"], lane: ["Gold Lane", "Jungler"], image: "/heroes/kimmy.png", winrate: 16 },
  { id: "kadita", name: "Kadita", role: ["Mage", "Assassin"], lane: ["Mid Lane", "Roamer"], image: "/heroes/kadita.png", winrate: 100 },
  { id: "lunox", name: "Lunox", role: ["Mage"], lane: ["Mid Lane", "Gold Lane"], image: "/heroes/lunox.png", winrate: 100 },
  { id: "luo-yi", name: "Luo Yi", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/luo_yi.png", winrate: 0 },
  { id: "lylia", name: "Lylia", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/lylia.png", winrate: 37 },
  { id: "nana", name: "Nana", role: ["Mage", "Support"], lane: ["Mid Lane"], image: "/heroes/nana.png", winrate: 0 },
  { id: "novaria", name: "Novaria", role: ["Mage"], lane: ["Mid Lane", "Roamer"], image: "/heroes/novaria.png", winrate: 0 },
  { id: "odette", name: "Odette", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/odette.png", winrate: 50 },
  { id: "pharsa", name: "Pharsa", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/pharsa.png", winrate: 63 },
  { id: "vale", name: "Vale", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/vale.png", winrate: 0 },
  { id: "valentina", name: "Valentina", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/valentina.png", winrate: 31 },
  { id: "valir", name: "Valir", role: ["Mage"], lane: ["Mid Lane", "Roamer"], image: "/heroes/valir.png", winrate: 50 },
  { id: "vexana", name: "Vexana", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/vexana.png", winrate: 100 },
  { id: "xavier", name: "Xavier", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/xavier.png", winrate: 0 },
  { id: "yve", name: "Yve", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/yve.png", winrate: 62 },
  { id: "zhask", name: "Zhask", role: ["Mage"], lane: ["Mid Lane", "Gold Lane"], image: "/heroes/zhask.png", winrate: 0 },
  { id: "zhuxin", name: "Zhuxin", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/zhuxin.png", winrate: 53 },
  { id: "zetian", name: "Zetian", role: ["Mage"], lane: ["Mid Lane"], image: "/heroes/zetian.png", winrate: 33 },

  // --- MARKSMAN ---
  { id: "beatrix", name: "Beatrix", role: ["Marksman"], lane: ["Gold Lane", "Mid Lane"], image: "/heroes/beatrix.png", winrate: 100 },
  { id: "brody", name: "Brody", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/brody.png", winrate: 100 },
  { id: "bruno", name: "Bruno", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/bruno.png", winrate: 0 },
  { id: "claude", name: "Claude", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/claude.png", winrate: 46 },
  { id: "clint", name: "Clint", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/clint.png", winrate: 0 },
  { id: "granger", name: "Granger", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/granger.png", winrate: 66 },
  { id: "hanabi", name: "Hanabi", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/hanabi.png", winrate: 0 },
  { id: "irithel", name: "Irithel", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/irithel.png", winrate: 0 },
  { id: "ixia", name: "Ixia", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/ixia.png", winrate: 0 },
  { id: "karrie", name: "Karrie", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/karrie.png", winrate: 47 },
  { id: "layla", name: "Layla", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/layla.png", winrate: 0 },
  { id: "melissa", name: "Melissa", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/melissa.png", winrate: 0 },
  { id: "miya", name: "Miya", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/miya.png", winrate: 0 },
  { id: "moskov", name: "Moskov", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/moskov.png", winrate: 80 },
  { id: "natan", name: "Natan", role: ["Marksman"], lane: ["Gold Lane", "Jungler"], image: "/heroes/natan.png", winrate: 0 },
  { id: "obsidia", name: "Obsidia", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/obsidia.png", winrate: 57 },
  { id: "popol-and-kupa", name: "Popol and Kupa", role: ["Marksman"], lane: ["Gold Lane", "Jungler", "Roamer"], image: "/heroes/popol_and_kupa.png", winrate: 0 },
  { id: "wanwan", name: "Wanwan", role: ["Marksman"], lane: ["Gold Lane"], image: "/heroes/wanwan.png", winrate: 0 },

  // --- SUPPORT ---
  { id: "angela", name: "Angela", role: ["Support"], lane: ["Roamer", "Mid Lane"], image: "/heroes/angela.png", winrate: 0 },
  { id: "carmilla", name: "Carmilla", role: ["Support", "Tank"], lane: ["Roamer", "Jungler"], image: "/heroes/carmilla.png", winrate: 0 },
  { id: "chip", name: "Chip", role: ["Support", "Tank"], lane: ["Roamer"], image: "/heroes/chip.png", winrate: 66 },
  { id: "diggie", name: "Diggie", role: ["Support"], lane: ["Roamer"], image: "/heroes/diggie.png", winrate: 0 },
  { id: "estes", name: "Estes", role: ["Support"], lane: ["Roamer"], image: "/heroes/estes.png", winrate: 0 },
  { id: "faramis", name: "Faramis", role: ["Support", "Mage"], lane: ["Mid Lane", "Roamer"], image: "/heroes/faramis.png", winrate: 100 },
  { id: "floryn", name: "Floryn", role: ["Support"], lane: ["Roamer"], image: "/heroes/floryn.png", winrate: 0 },
  { id: "kaja", name: "Kaja", role: ["Support", "Fighter"], lane: ["Roamer", "EXP Lane"], image: "/heroes/kaja.png", winrate: 100 },
  { id: "mathilda", name: "Mathilda", role: ["Support", "Assassin"], lane: ["Roamer", "Mid Lane"], image: "/heroes/mathilda.png", winrate: 0 },
  { id: "marcel", name: "Marcel", role: ["Support"], lane: ["Roamer"], image: "/heroes/marcel.png", winrate: 70 },
  { id: "rafaela", name: "Rafaela", role: ["Support"], lane: ["Roamer"], image: "/heroes/rafaela.png", winrate: 0 },
];